// Decoding, against bytes the server actually sent.
//
// These fixtures are bytes the server sent, captured by
// `scripts/capture-companion-fixtures.mjs` against a harness started on a
// temporary HOME. That matters more than it sounds: hand-written test JSON
// tests our idea of the API, and the whole risk in a two-language client is
// that our idea drifts from the API without anything failing. When a server
// payload changes, re-capturing makes these fail, which is the alarm.
//
// One exception, and it is marked in the script: options-card.json needs a
// bot to actually ask for approval, which needs a real provider and a real
// turn, so it is not regenerated by a run.
import XCTest
@testable import CompanionCore

final class DecodingTests: XCTestCase {
    // MARK: - Fixtures

    func fixture(_ name: String) throws -> Data {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: name, withExtension: "json")
        else {
            XCTFail("missing fixture \(name).json — run scripts/capture-companion-fixtures.mjs")
            throw CocoaError(.fileNoSuchFile)
        }
        return try Data(contentsOf: url)
    }

    func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONDecoder().decode(type, from: try fixture(name))
    }

    // MARK: - Hydration

    func testDecodesThePagedFleet() throws {
        let fleet = try decode(Fleet.self, "bots-paged")
        XCTAssertFalse(fleet.bots.isEmpty)

        let bot = try XCTUnwrap(fleet.bots.first)
        XCTAssertFalse(bot.id.isEmpty)
        XCTAssertFalse(bot.threadId.isEmpty)
        XCTAssertFalse(bot.name.isEmpty)
        XCTAssertNotNil(bot.messages)

        // the paged shape caps each thread and says whether there is more
        let room = try XCTUnwrap(fleet.groups.first)
        XCTAssertEqual(room.messages?.count, 3)
        XCTAssertEqual(room.hasMore, true)
    }

    func testDecodesTheFullFleetToo() throws {
        // omitting ?messages must stay decodable by the same types — it is
        // what the desktop gets, and what a phone falls back to
        let fleet = try decode(Fleet.self, "bots-full")
        XCTAssertFalse(fleet.bots.isEmpty)
        XCTAssertNil(fleet.bots.first?.hasMore)
    }

    func testOldAndNewAvatarProfilesDecodeTogether() throws {
        let oldBot = try XCTUnwrap(decode(Fleet.self, "bots-full").bots.first)
        XCTAssertNil(oldBot.avatarUrl)
        XCTAssertNil(oldBot.avatarCrop)

        let newBot = try XCTUnwrap(decode(Fleet.self, "bot-avatar-profile").bots.first)
        XCTAssertEqual(newBot.avatarUrl, "/api/attachments/123e4567-e89b-12d3-a456-426614174000.webp")
        XCTAssertEqual(newBot.avatarCrop, .rounded)
        XCTAssertEqual(newBot.voice, "voice-1")
        XCTAssertEqual(newBot.speakReplies, true)
    }

    func testMascotShapeDecodesAndUnknownValuesUseTheDropletDefault() throws {
        let json = """
        {
          "id":"shape-bot","threadId":"shape-thread","name":"Shape","title":"",
          "description":"","notifications":true,"color":"purple","mascotShape":"hexagon",
          "unread":false,"modelSelection":{"instanceId":"local","model":"default"},"createdAt":1
        }
        """
        let bot = try JSONDecoder().decode(Bot.self, from: Data(json.utf8))
        XCTAssertEqual(bot.mascotShape, .hexagon)

        let future = try JSONDecoder().decode(
            Bot.self,
            from: Data(json.replacingOccurrences(of: #""mascotShape":"hexagon""#, with: #""mascotShape":"star""#).utf8)
        )
        XCTAssertEqual(future.mascotShape, .droplet)
    }

    func testGrokMascotPaletteIncludesLightColorsAndUnknownBotsUseSafeGreen() throws {
        XCTAssertEqual(
            Set(MausColor.allCases),
            Set([.green, .blue, .red, .orange, .purple, .cyan, .pink, .yellow, .teal, .coral, .white, .brown, .gray])
        )

        let json = """
        {
          "id":"palette-bot","threadId":"palette-thread","name":"Palette","title":"",
          "description":"","notifications":true,"color":"chartreuse",
          "unread":false,"modelSelection":{"instanceId":"local","model":"default"},"createdAt":1
        }
        """
        let bot = try JSONDecoder().decode(Bot.self, from: Data(json.utf8))
        XCTAssertEqual(bot.mascotColor, .green)
    }

    func testRuntimeActivityControlsMascotMotionEligibility() throws {
        let json = """
        {
          "id":"activity-bot","threadId":"activity-thread","name":"Activity",
          "title":"","description":"","notifications":true,"color":"green",
          "activity":"waiting-on-you","busy":true,"unread":false,
          "modelSelection":{"instanceId":"local","model":"default"},"createdAt":1
        }
        """
        let waiting = try JSONDecoder().decode(Bot.self, from: Data(json.utf8))
        XCTAssertFalse(waiting.isWorking)

        let working = try JSONDecoder().decode(
            Bot.self,
            from: Data(json.replacingOccurrences(of: "waiting-on-you", with: "working").utf8)
        )
        XCTAssertTrue(working.isWorking)

        let legacy = try JSONDecoder().decode(
            Bot.self,
            from: Data(json.replacingOccurrences(of: #""activity":"waiting-on-you","busy":true"#, with: #""busy":true"#).utf8)
        )
        XCTAssertTrue(legacy.isWorking)
    }

    func testFutureAvatarCropFallsBackWithoutDroppingTheBot() throws {
        let fixture = String(decoding: try fixture("bot-avatar-profile"), as: UTF8.self)
            .replacingOccurrences(of: #""avatarCrop":"rounded""#, with: #""avatarCrop":"hexagon""#)
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(fixture.utf8))

        XCTAssertEqual(fleet.bots.count, 1)
        XCTAssertEqual(fleet.bots.first?.avatarCrop, .mascot)
    }

    func testFutureRoutineScheduleKindRemainsVisibleAsUnknown() throws {
        let schedule = try JSONDecoder().decode(
            RoutineSchedule.self,
            from: Data(#"{"type":"weekly","time":"09:00","weekdays":[1]}"#.utf8)
        )

        XCTAssertEqual(schedule.type, .unknown)
        XCTAssertEqual(schedule.time, "09:00")
        XCTAssertEqual(schedule.weekdays, [1])
    }

    func testNotificationTargetRequiresBothExactIds() {
        XCTAssertEqual(
            NotificationTarget(payload: ["botId": "bot-1", "threadId": "detached-task-2"]),
            NotificationTarget(botId: "bot-1", threadId: "detached-task-2")
        )
        XCTAssertNil(NotificationTarget(payload: ["botId": "bot-1"]))
        XCTAssertNil(NotificationTarget(payload: ["threadId": "task-1"]))
        XCTAssertNil(NotificationTarget(botId: " ", threadId: "task-1"))
        guard let detached = NotificationTarget(botId: "bot-1", threadId: "task-2") else {
            return XCTFail("valid notification target")
        }
        XCTAssertTrue(detached.requiresTaskSwitch(activeThreadId: "task-1"))
        XCTAssertFalse(detached.requiresTaskSwitch(activeThreadId: "task-2"))
    }

    func testDecodesTheCloudBackendAndItsAbsence() throws {
        // The cloud-desktop button hides on cloudBackend == "vps", so both
        // sides of that gate must decode: a harness that sends the field, and
        // an older one that has never heard of it (nil keeps the button).
        let json = """
        {
          "bots": [
            {
              "id":"b1","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1,
              "computer":"cloud","cloudBackend":"vps"
            },
            {
              "id":"b2","threadId":"t2","name":"Rio","title":"","description":"",
              "notifications":true,"color":"blue","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":2,
              "computer":"cloud"
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.first?.cloudBackend, "vps")
        XCTAssertNil(fleet.bots.last?.cloudBackend)
    }

    func testDecodesMultipleConnectedAccountsAndNoAuthToolkit() throws {
        let payload = #"""
        {
          "configured": true,
          "services": {
            "gmail": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": [
                {"id": "ca_work", "alias": "Work", "status": "ACTIVE"},
                {"id": "ca_personal", "status": "INACTIVE"}
              ]
            },
            "weather": {
              "connected": true,
              "pending": false,
              "status": "ACTIVE",
              "accounts": []
            },
            "slack": {
              "connected": false,
              "pending": true
            }
          }
        }
        """#
        let statuses = try JSONDecoder().decode(ConnectorStatuses.self, from: Data(payload.utf8))
        let gmail = try XCTUnwrap(statuses.services["gmail"])
        XCTAssertEqual(gmail.accounts?.map(\.id), ["ca_work", "ca_personal"])
        XCTAssertEqual(gmail.accounts?.first?.alias, "Work")
        XCTAssertNil(gmail.accounts?.last?.alias)
        XCTAssertTrue(try XCTUnwrap(gmail.accounts?.first).isActive)
        XCTAssertFalse(try XCTUnwrap(gmail.accounts?.last).isActive)

        let noAuth = try XCTUnwrap(statuses.services["weather"])
        XCTAssertTrue(noAuth.connected)
        XCTAssertEqual(noAuth.accounts?.isEmpty, true)

        let pending = try XCTUnwrap(statuses.services["slack"])
        XCTAssertEqual(pending.pending, true)
        XCTAssertNil(pending.accounts)
    }

    func testOneMalformedBotDoesNotHideTheRestOfTheFleet() throws {
        let json = """
        {
          "bots": [
            {"id":"broken","threadId":42},
            {
              "id":"good","threadId":"t1","name":"Scout","title":"","description":"",
              "notifications":true,"color":"green","unread":false,
              "modelSelection":{"instanceId":"i1","model":"m1"},"createdAt":1
            }
          ],
          "groups": []
        }
        """
        let fleet = try JSONDecoder().decode(Fleet.self, from: Data(json.utf8))
        XCTAssertEqual(fleet.bots.map(\.id), ["good"])
    }

    func testNeverDecodesProviderSessionCursors() throws {
        // resumeCursors is harness bookkeeping and must not be on the wire.
        // Asserted against the raw bytes, because a Swift type that simply
        // lacks the field would hide it.
        for name in ["bots-full", "bots-paged", "sse-frames"] {
            let raw = String(decoding: try fixture(name), as: UTF8.self)
            XCTAssertFalse(raw.contains("resumeCursors"), "\(name) carries provider session cursors")
        }
    }

    func testDecodesAThreadPage() throws {
        let page = try decode(ThreadPage.self, "thread-page")
        XCTAssertEqual(page.messages.count, 2)
        XCTAssertEqual(page.hasMore, true)
        // pages arrive oldest-first, which is what makes prepending correct
        let times = page.messages.map(\.at)
        XCTAssertEqual(times, times.sorted())
    }

    // MARK: - Messages and cards

    func testDecodesAnOptionsCard() throws {
        let message = try decode(Message.self, "options-card")
        XCTAssertEqual(message.kind, .options)
        XCTAssertEqual(message.role, .bot)
        let card = try XCTUnwrap(message.card)
        XCTAssertFalse(card.options.isEmpty)
        // the onboarding card has no request behind it, so it is history
        XCTAssertFalse(card.isPending)
        XCTAssertFalse(card.isPermission)
    }

    func testAPendingApprovalIsActionableAndAnAnsweredOneIsNot() throws {
        // The shape a live permission request takes, which the fixture rig
        // cannot produce without a real provider attached.
        let json = """
        {
          "id": "m1", "role": "bot", "kind": "options", "at": 1786742413762,
          "card": {
            "title": "Approval needed", "subtitle": "rm -rf ./build",
            "options": ["Allow", "Deny"], "requestId": "req-1",
            "tool": "Bash", "allowKey": "Bash:rm"
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertTrue(card.isPending)
        XCTAssertTrue(card.isPermission)
        XCTAssertEqual(card.allowKey, "Bash:rm")
        XCTAssertEqual(card.responseBehavior(for: "Allow"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Approve"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Yes"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Always allow"), "allow")
        XCTAssertEqual(card.responseBehavior(for: "Deny"), "deny")
        XCTAssertEqual(card.responseBehavior(for: " deny "), "deny")
        XCTAssertTrue(card.shouldRememberPermission(for: "Always allow"))
        XCTAssertFalse(card.shouldRememberPermission(for: "Allow"))
        XCTAssertFalse(card.shouldRememberPermission(for: " deny "))

        var answered = card
        answered.answered = "Allow"
        XCTAssertFalse(answered.isPending, "an answered card must stop offering buttons")

        var dismissed = card
        dismissed.dismissed = true
        XCTAssertFalse(dismissed.isPending)
    }

    func testPermissionCardKeepsFriendlyHeadlineAndDisclosureDetailsSeparate() throws {
        let json = """
        {
          "id": "m-permission", "role": "bot", "kind": "options", "at": 1,
          "card": {
            "title": "Allow Terminal on Mac mini?",
            "subtitle": "This will let Terminal run on Mac mini.",
            "options": ["Allow", "Deny"], "requestId": "req-2", "tool": "Bash",
            "toolLabel": "Terminal", "hostLabel": "Mac mini",
            "actionSummary": "This will let Terminal run on Mac mini.",
            "alwaysAllowSummary": "Always allow Terminal to run git commands on Mac mini.",
            "details": "git status --short", "allowKey": "Bash:git"
          }
        }
        """
        let card = try XCTUnwrap(try JSONDecoder().decode(Message.self, from: Data(json.utf8)).card)
        XCTAssertEqual(card.toolLabel, "Terminal")
        XCTAssertEqual(card.hostLabel, "Mac mini")
        XCTAssertEqual(card.actionSummary, "This will let Terminal run on Mac mini.")
        XCTAssertEqual(card.alwaysAllowSummary, "Always allow Terminal to run git commands on Mac mini.")
        XCTAssertEqual(card.details, "git status --short")
        XCTAssertEqual(card.displayLabel(for: "Allow"), "Allow")
        XCTAssertEqual(card.displayLabel(for: "Deny"), "Deny")
        XCTAssertEqual(card.displayLabel(for: "Always allow"), "Always allow")
        XCTAssertEqual(card.permissionAllowChoice, "Allow")
        XCTAssertEqual(card.permissionDenyChoice, "Deny")
        XCTAssertNil(card.permissionStandingGrantChoice)

        var standing = card
        standing.options = ["Allow", "Deny", "Always allow"]
        XCTAssertEqual(standing.permissionStandingGrantChoice, "Always allow")
        XCTAssertEqual(standing.displayLabel(for: "Always allow"), "Always allow")
    }

    func testAQuestionSendsItsChoiceAsAnAnswer() throws {
        let message = try decode(Message.self, "options-card")
        let card = try XCTUnwrap(message.card)
        XCTAssertFalse(card.isPermission)
        XCTAssertEqual(card.responseBehavior(for: "Anything"), "answer")
        XCTAssertFalse(card.shouldRememberPermission(for: "Always allow"))
    }

    func testPermissionPresentationRemovesLegacyHostInternals() {
        let raw = "Run on mini [bd3ebe13-54d5-4cf7-9bbe-1b17ea4ac4b5] via http://127.0.0.1:5900/?token=secret"
        let clean = OptionCard.sanitizedPresentation(raw)
        XCTAssertEqual(clean, "Run on mini via [redacted link]")
        XCTAssertFalse(clean.contains("bd3ebe13"))
        XCTAssertFalse(clean.contains("127.0.0.1"))
    }

    func testDecodesAMessageThatGainedAFieldWeDoNotKnow() throws {
        // The harness ships ahead of the app. An unknown key must not cost
        // the user their conversation.
        let json = """
        {"id":"m2","role":"user","kind":"text","at":1,"text":"hi","somethingNew":{"a":1}}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.text, "hi")
    }

    // MARK: - Pairing and errors

    func testDecodesThePairResponse() throws {
        let paired = try decode(PairResponse.self, "pair-response")
        XCTAssertTrue(paired.token.hasPrefix("omb_"))
        XCTAssertEqual(paired.device.name, "Ada's iPhone")
        XCTAssertFalse(paired.serverName.isEmpty)
    }

    func testMalformedAdvisoryEndpointDoesNotDiscardAPairedToken() throws {
        let json = """
        {
          "token":"omb_device",
          "device":{"id":"d1","name":"Ada's iPhone","createdAt":1,"lastSeenAt":1},
          "serverName":"Ada's Mac",
          "hosts":["192.168.1.42"],
          "endpoints":[
            {"url":"https://mac.example","kind":"hosted","priority":0},
            {"url":"https://future.example","kind":"future-transport","priority":10},
            {"url":"http://192.168.1.42:8810","kind":"lan","priority":200}
          ]
        }
        """

        let paired = try JSONDecoder().decode(PairResponse.self, from: Data(json.utf8))

        XCTAssertEqual(paired.token, "omb_device")
        XCTAssertEqual(paired.hosts, ["192.168.1.42"])
        XCTAssertEqual(paired.endpoints?.map(\.kind), [.hosted, .lan])
    }

    func testDecodesTheHarnessErrorBodies() throws {
        // These are captured server contracts. Keep them verbatim until the
        // desktop changes in lockstep; the client passes them through.
        XCTAssertEqual(
            try decode(APIErrorBody.self, "unauthorized").error,
            "pair this device from Phone settings in OpenMausBot on your computer"
        )
        XCTAssertFalse(try decode(APIErrorBody.self, "forbidden").error.isEmpty)
        XCTAssertEqual(
            try decode(APIErrorBody.self, "pair-rejected").error,
            "no pairing is in progress — open Phone settings on your computer"
        )
    }

    func testDecodesInstancesAndConfig() throws {
        let instances = try decode(InstanceList.self, "instances").instances
        // Availability is a property of the machine that captured the
        // fixture, not of the wire contract. Pin the required identity and
        // catalog shape without making a developer's installed CLIs decide
        // whether this test passes.
        let instance = try XCTUnwrap(instances.first)
        XCTAssertFalse(instance.instanceId.isEmpty)
        XCTAssertFalse(instance.driverKind.isEmpty)

        let config = try decode(ConfigStatus.self, "config")
        XCTAssertEqual(config.profile?.name, "Ada Lovelace")
        XCTAssertEqual(config.box?.configured, false)
    }

    // MARK: - Frames

    func testDecodesEveryCapturedFrame() throws {
        let frames = try decode([StreamFrame].self, "sse-frames")
        XCTAssertFalse(frames.isEmpty)

        var kinds: [String] = []
        for streamFrame in frames {
            switch streamFrame.frame {
            case let .hello(cursor, resumed):
                kinds.append("hello")
                XCTAssertTrue(cursor.contains(":"))
                XCTAssertFalse(resumed, "a cold connection has nothing to resume")
                XCTAssertNil(streamFrame.seq, "hello is not a replayable frame")
            case let .message(threadId, message):
                kinds.append("message")
                XCTAssertFalse(threadId.isEmpty)
                XCTAssertFalse(message.id.isEmpty)
                XCTAssertNotNil(streamFrame.seq)
            case let .bot(bot):
                kinds.append("bot")
                XCTAssertFalse(bot.id.isEmpty)
                XCTAssertNil(bot.messages, "bot frames carry no transcript")
            case let .unknown(kind):
                XCTFail("unhandled frame kind in fixtures: \(kind)")
            default:
                kinds.append("other")
            }
        }
        XCTAssertTrue(kinds.contains("hello"))
        XCTAssertTrue(kinds.contains("message"))
        XCTAssertTrue(kinds.contains("bot"))
    }

    func testAnUnknownFrameKindIsAbsorbedRatherThanThrown() throws {
        // the harness will add frame kinds; an old app must keep folding the
        // ones it knows instead of tearing down its stream
        let frame = try JSONDecoder().decode(
            StreamFrame.self,
            from: Data(#"{"kind":"routine.run","run":{"id":"r1"},"seq":9}"#.utf8)
        )
        XCTAssertEqual(frame.seq, 9)
        guard case let .unknown(kind) = frame.frame else {
            return XCTFail("expected .unknown, got \(frame.frame)")
        }
        XCTAssertEqual(kind, "routine.run")
    }

    func testDecodesARuntimeDeltaWithEventId() throws {
        let json = """
        {"kind":"runtime","seq":4,"event":{
          "type":"content.delta","threadId":"t1","delta":"Hel",
          "streamKind":"assistant_text","eventId":"e1"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .runtime(event) = frame.frame else {
            return XCTFail("expected .runtime")
        }
        XCTAssertEqual(event.eventId, "e1")
        XCTAssertEqual(event.delta, "Hel")
        XCTAssertEqual(event.streamKind, "assistant_text")
    }

    func testDecodesANotifyFrame() throws {
        let json = """
        {"kind":"notify","seq":12,"notification":{
          "kind":"approval","botId":"b1","botName":"Scout","threadId":"t1",
          "title":"Scout needs approval","body":"rm -rf ./build"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .notify(notification) = frame.frame else {
            return XCTFail("expected .notify")
        }
        XCTAssertTrue(notification.isBlocking)
        XCTAssertEqual(notification.threadId, "t1")
        XCTAssertEqual(frame.frame.threadId, "t1")
    }

    // MARK: - A newer computer than the phone

    // The harness gains message kinds when it ships; the phone gains them
    // when the App Store gets round to it. So the phone talking to a newer
    // computer is the ordinary case, and it must survive one.

    func testAnUnknownMessageKindDecodes() throws {
        let json = """
        {"id":"m1","role":"bot","kind":"webhook","at":1,"text":"Stripe fired"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.kind, .unknown)
        // and keeps what it can show
        XCTAssertEqual(message.text, "Stripe fired")
    }

    func testAnUnknownRoleIsNotAttributedToYou() throws {
        let json = """
        {"id":"m1","role":"system","kind":"text","at":1,"text":"hello"}
        """
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.role, .bot)
    }

    /// The one that matters. `kind` is not optional, so before this a single
    /// unrecognised message failed the decode of the entire response — the
    /// thread did not render one message oddly, it did not render.
    func testOneUnknownMessageDoesNotSinkThePage() throws {
        let json = """
        {"messages":[
          {"id":"m1","role":"user","kind":"text","at":1,"text":"go"},
          {"id":"m2","role":"bot","kind":"something-new","at":2,"text":"working"},
          {"id":"m3","role":"bot","kind":"text","at":3,"text":"done"}
        ],"hasMore":false}
        """
        let page = try JSONDecoder().decode(ThreadPage.self, from: Data(json.utf8))
        XCTAssertEqual(page.messages.count, 3)
        XCTAssertEqual(page.messages.map(\.kind), [.text, .unknown, .text])
        XCTAssertEqual(page.messages.map(\.id), ["m1", "m2", "m3"])
    }

    /// Same page, arriving one message at a time down the stream.
    func testAnUnknownMessageArrivesOverTheStream() throws {
        let json = """
        {"kind":"message","seq":3,"threadId":"t1",
         "message":{"id":"m9","role":"bot","kind":"routine.run","at":9,"text":"ran"}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .message(threadId, message) = frame.frame else {
            return XCTFail("expected .message, got \(frame.frame)")
        }
        XCTAssertEqual(threadId, "t1")
        XCTAssertEqual(message.kind, .unknown)
        XCTAssertEqual(message.text, "ran")
    }

    func testDecodesASanitizedHermesSubagentFrameWithoutRuntimeIds() throws {
        let json = """
        {"kind":"hermes.subagent","seq":8,"activity":{
          "activityId":"act-1","parentThreadId":"parent-thread","title":"Draft review",
          "status":"started","transcriptThreadId":"thread-temp-1","promoteEligible":false,
          "updatedAt":1700000000000}}
        """
        let frame = try JSONDecoder().decode(StreamFrame.self, from: Data(json.utf8))
        guard case let .hermesSubagent(activity) = frame.frame else {
            return XCTFail("expected .hermesSubagent, got \(frame.frame)")
        }
        XCTAssertEqual(activity.activityId, "act-1")
        XCTAssertEqual(activity.parentThreadId, "parent-thread")
        XCTAssertEqual(activity.transcriptThreadId, "thread-temp-1")
        XCTAssertEqual(activity.status, .started)
        XCTAssertEqual(activity.updatedAt, 1_700_000_000_000)
        XCTAssertEqual(frame.frame.threadId, "thread-temp-1")
        XCTAssertFalse(json.contains("hermesAgentId"))
        XCTAssertFalse(json.contains("moa-temp"))
        XCTAssertFalse(json.lowercased().contains("token"))
        XCTAssertFalse(json.lowercased().contains("sk-"))
    }

    func testDecodesOAuthConnectorCardWithoutExposingCredentialText() throws {
        let json = #"""
        {
          "id":"connect-1","role":"bot","kind":"connector","at":1,
          "connector":{
            "slug":"google_calendar","label":"Google Calendar",
            "description":"Connect with OAuth. apiKey=sk-live-never-show-this",
            "status":"required","resumeKey":"calendar-read",
            "logo":"https://cdn.example.com/google.png","domain":"google.com",
            "error":"access_token=secret-token"
          }
        }
        """#
        let message = try JSONDecoder().decode(Message.self, from: Data(json.utf8))
        XCTAssertEqual(message.kind, .connector)
        let card = try XCTUnwrap(message.connector)
        XCTAssertTrue(card.isUsable)
        XCTAssertEqual(card.label, "Google Calendar")
        XCTAssertEqual(card.safeLogoURL?.scheme, "https")
        XCTAssertTrue(card.displayDescription.contains("•••"))
        XCTAssertFalse(card.displayDescription.contains("sk-live-never-show-this"))
        XCTAssertTrue(card.displayError?.contains("•••") == true)
        XCTAssertFalse(card.displayError?.contains("secret-token") == true)
    }

    func testMalformedOrSecretCardsRemainNonActionable() throws {
        let malformed = #"{"id":"m1","role":"bot","kind":"connector","at":1,"connector":"not-an-object","text":"Connect in OpenMausBot on your computer"}"#
        let malformedMessage = try JSONDecoder().decode(Message.self, from: Data(malformed.utf8))
        XCTAssertEqual(malformedMessage.kind, .connector)
        XCTAssertFalse(try XCTUnwrap(malformedMessage.connector).isUsable)

        let secret = #"{"id":"m2","role":"bot","kind":"secret","at":2,"secret":{"value":"do-not-send"},"text":"Use the desktop settings"}"#
        let secretMessage = try JSONDecoder().decode(Message.self, from: Data(secret.utf8))
        XCTAssertEqual(secretMessage.kind, .unknown)
        XCTAssertNil(secretMessage.connector)
        XCTAssertEqual(secretMessage.text, "Use the desktop settings")
    }
}
